type: string
description: |-
  Nhóm sản phẩm theo thị trường.

  - `UNSPECIFIED`: Không xác định
  - `FBX`: Hợp đồng tương lai Trái phiếu
  - `FIO`: Hợp đồng tương lai Chỉ số
  - `HCX`: Trái phiếu Doanh nghiệp HNX
  - `STO`: Cổ phiếu sàn HOSE
  - `STX`: Cổ phiếu sàn HNX
  - `UPX`: Cổ phiếu sàn Upcom
enum:
  - UNSPECIFIED
  - FBX
  - FIO
  - HCX
  - STO
  - STX
  - UPX
example: STO
